// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FAdminContent: typeof import('./src/components/layouts/FAdminContent.vue')['default']
    FAdminLayout: typeof import('./src/components/layouts/FAdminLayout.vue')['default']
    FAuthCenterLayout: typeof import('./src/components/layouts/FAuthCenterLayout.vue')['default']
    FAuthSidedLayout: typeof import('./src/components/layouts/FAuthSidedLayout.vue')['default']
    FSpace: typeof import('./src/components/layouts/FSpace.vue')['default']
    IFiiMenu: typeof import('~icons/fii/menu')['default']
    IFiiPerson: typeof import('~icons/fii/person')['default']
    IFiiPower: typeof import('~icons/fii/power')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
