// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FAdminContent: typeof import('./components/layouts/FAdminContent.vue')['default']
    FAdminLayout: typeof import('./components/layouts/FAdminLayout.vue')['default']
    FAuthCenterLayout: typeof import('./components/layouts/FAuthCenterLayout.vue')['default']
    FAuthSidedLayout: typeof import('./components/layouts/FAuthSidedLayout.vue')['default']
    FBtn: typeof import('./components/buttons/FBtn.vue')['default']
    FCard: typeof import('./components/cards/FCard.vue')['default']
    FCheckbox: typeof import('./components/forms/FCheckbox.vue')['default']
    FConfirm: typeof import('./components/messages/FConfirm.vue')['default']
    FDataTable: typeof import('./components/tables/FDataTable.vue')['default']
    FDrawer: typeof import('./components/drawers/FDrawer.vue')['default']
    FDropdown: typeof import('./components/menu/FDropdown.vue')['default']
    FFileInput: typeof import('./components/forms/FFileInput.vue')['default']
    FFormGroup: typeof import('./components/forms/FFormGroup.vue')['default']
    FMenu: typeof import('./components/menu/FMenu.vue')['default']
    FModal: typeof import('./components/modals/FModal.vue')['default']
    FPagination: typeof import('./components/tables/FPagination.vue')['default']
    FPasswordInput: typeof import('./components/forms/FPasswordInput.vue')['default']
    FRadioButton: typeof import('./components/forms/FRadioButton.vue')['default']
    FSearchInput: typeof import('./components/forms/FSearchInput.vue')['default']
    FSelectInput: typeof import('./components/forms/FSelectInput.vue')['default']
    FSimpleTable: typeof import('./components/tables/FSimpleTable.vue')['default']
    FSpace: typeof import('./components/layouts/FSpace.vue')['default']
    FTestMenu: typeof import('./components/menu/FTestMenu.vue')['default']
    FTextInput: typeof import('./components/forms/FTextInput.vue')['default']
    FTextMenu: typeof import('./components/menu/FTextMenu.vue')['default']
    FToast: typeof import('./components/messages/FToast.vue')['default']
    FTooltip: typeof import('./components/menu/FTooltip.vue')['default']
    IFiiClose: typeof import('~icons/fii/close')['default']
    IFiiMenu: typeof import('~icons/fii/menu')['default']
    IFiiPerson: typeof import('~icons/fii/person')['default']
    IFiiPower: typeof import('~icons/fii/power')['default']
    IFiiSearch: typeof import('~icons/fii/search')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
